meta:
  title: medirae 
  description: Dynamic and customizable jekyll theme

user:
  username-prefix: its
  username: '<span style="color: #4c6349;">m</span>edi<span style="color: #4c6349;">r</span>ae'
  name: Medi Rafiei
  short-description: '<span style="color: #d1443d;">enthusiastic</span> • <span style="color: #e38b3d;">adventurous</span>'
  title: programmer

about:
  description: >
    Hi there, I'm a progammer based in Isfahan, Iran; passionate about
    open-source software, systems programming, and tooling & tinkering.
    Currently I'm working on my personal development ecosystem,
    and brushing up on my web development skills.
    <br>Anyhow, let's get going with the professional button-pressing, shall we?

footer:
  quote: 'Never give up without a fight. <span style="color: #857676;">&General Iroh</span>'

theme: jekyll-github-pages
theme-version: 0.1.13
